name: taskly
description: "Task Manager Application for Android, IOS & Linux"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  fluttertoast: ^8.2.8
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: poppins
      fonts:
        - asset: fonts/poppins.ttf
